sudo: required

language: generic

services:
  - docker

before_install:
  - docker-compose build

script:
    ./run-tests.sh

notifications:
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/5ad7b48d1cea3eb74221
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
