language: c

before_script:
    - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' > /etc/apt/sources.list.d/mono-xamarin.list"
    - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
    - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
    - sudo apt-get update -qq
    - sudo apt-get install --force-yes mono-devel emacs-snapshot emacs-snapshot-el npm
    - npm i omnisharp-server-roslyn-binaries
    - cd node_modules/omnisharp-server-roslyn-binaries
    - mono --version
    - cd test/MinimalSolution
    - ../../node_modules/omnisharp-server-roslyn-binaries/lib/server/omnisharp
    - cd ..
    - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
    - export PATH="/home/travis/.cask/bin:$PATH"
    - emacs --version
    - cask
    
script:
    ./run-entire-travis-build.sh
