language: csharp
mono:
- beta

install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh
  | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade

before_script:
    - curl -fsSkL https://gist.github.com/rejeep/7736123/raw > travis.sh && source ./travis.sh
    - evm list
    - emacs --version
    - cask install
    - mkdir omnisharp-roslyn
    - cd omnisharp-roslyn
    - wget $(curl -s https://api.github.com/repos/omnisharp/omnisharp-roslyn/releases/latest | grep browser_download_url | awk '{ print $2 }' | sed s/\"//g | sed s/,//g)
    - tar xzvf omnisharp.tar.gz
    - cd ..
    - mono --version

script:
    ./run-entire-travis-build.sh
