language: csharp
mono:
- beta

install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh
  | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade

before_script:
    - curl -fsSkL https://gist.github.com/rejeep/7736123/raw > travis.sh && source ./travis.sh
    - evm list
    - emacs --version
    - cask install
    - mkdir omnisharp-roslyn
    - cd omnisharp-roslyn
    - wget https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.0.3/omnisharp.tar.gz
    - tar xzvf omnisharp.tar.gz
    - cd ..
    - mono --version

script:
    ./run-entire-travis-build.sh
