language: csharp
mono:
- beta

install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh
  | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade

before_script:
    - curl -fsSkL https://gist.github.com/ianbattersby/c3399aa8cd9e2a6f8afa/raw > travis.sh && source ./travis.sh
    - evm list
    - emacs --version
    - cask install
    - mono --version
    - cd travis-stuff
    - ./install-omnisharp-roslyn.sh
    - cd ..

script:
    ./run-entire-travis-build.sh

notifications:
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/5ad7b48d1cea3eb74221
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
