version: '3.3'
services:
  base: &base
    build:
      context: .
      dockerfile: Dockerfile.testing
    volumes:
      - '.:/tmp/src'
  tests:
    <<: *base
    command: bash -c "cp /tmp/src/*.el /usr/src/ && cp /tmp/src/test/*.el /usr/src/test/ && cp -r /tmp/src/test/buttercup-tests /usr/src/test/ && sh ./run-tests.sh"
  integration-tests:
    <<: *base
    command: bash -c "cp /tmp/src/*.el /usr/src/ && cp /tmp/src/test/*.el /usr/src/test/ && cp -r /tmp/src/test/buttercup-tests /usr/src/test/ && sh ./run-integration-tests.sh"
  melpa-build-test:
    <<: *base
    command: ./run-melpa-build-test.sh
